--- a/.github/workflows/ci-templates.yml
+++ b/.github/workflows/ci-templates.yml
@@ -49,15 +49,15 @@
         run: |
           echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
       - uses: actions/cache@v4
-        name: 鈾伙笍 Setup pnpm cache
+        name: Setup pnpm cache
         with:
           path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
           key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
           restore-keys: |
             ${{ runner.os }}-pnpm-store-
 
-      - name: 馃摜 Install
+      - name: Install
         run: pnpm install --no-frozen-lockfile
 
-      - name: 馃彈 Run build
-        run: pnpm build
+      - name: Run build
+        run: pnpm build